return function()
    require("trouble").setup {
        icons = {
            indent = {
                top = "│ ",
                middle = "├╴",
                -- last          = "└╴",
                last = "╰╴",
                fold_open = " ",
                fold_closed = " ",
                ws = "  ",
            },
            folder_closed = " ",
            folder_open = " ",
            kinds = {
                Array = " ",
                Boolean = "󰨙 ",
                Class = " ",
                Constant = "󰏿 ",
                Constructor = " ",
                Enum = " ",
                EnumMember = " ",
                Event = " ",
                Field = " ",
                File = " ",
                Function = "󰊕 ",
                Interface = " ",
                Key = " ",
                Method = "󰊕 ",
                Module = " ",
                Namespace = "󰦮 ",
                Null = " ",
                Number = "󰎠 ",
                Object = " ",
                Operator = " ",
                Package = " ",
                Property = " ",
                String = " ",
                Struct = "󰆼 ",
                TypeParameter = " ",
                Variable = "󰀫 ",
            },
        },
        modes = {
            lsp = {
                win = { position = "right" },
            },
        },
    }
end
